# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    rm -rf node_modules package-lock.json
    echo "🔄 Cleaned node_modules and lock file"
  displayName: 'Clean node_modules'

- script: |
    npm install
    echo "✅ Dependencies installed"
  displayName: 'Install Dependencies'

- script: |
    npm run build
  displayName: 'Run Build Script'
